[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deepstructgenomics-ncbi"
version = "0.2.0"
description = "Pipeline ARN/genomique reliant sequence -> structure -> impact a partir des donnees NCBI."
authors = [
  {name = "DeeW69"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "requests>=2.31",
  "numpy>=1.24",
  "biopython>=1.83",
  "vtk>=9.2"
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
homepage = "https://github.com/DeeW69/__DeepStructGenomics-NCBI"

[tool.setuptools.packages.find]
include = ["deepstructgenomics*"]
