[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deepstructgenomics-ncbi"
version = "0.1.0"
description = "Pipeline ARN/genomique reliant sequence -> structure -> impact a partir des donnees NCBI."
authors = [
  {name = "DeepStructGenomics Team"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "requests>=2.31",
  "numpy>=1.24",
  "biopython>=1.83",
  "vtk>=9.2"
]
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/DeepStructGenomics/DeepStructGenomics-NCBI"
